Migrating to TypeScript
Yekaterinburg-Tree-Map/ekbtrees-frontend pull request #12
Opened 2021-10-01 15:53 UTC by KachusovStepan

2021-10-06 05:56 UTC, AlekseyAnt requested changes

2021-10-06 05:56 UTC, AlekseyAnt commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +            .sort((first: any, second: any) => {
думаю стоить более точно определить тип (во всех файлах)

2021-10-06 05:56 UTC, AlekseyAnt commented on src/interfaces/user/User.ts
> +export interface User {
интерфейсы лучше писать с "I": IUser

2021-10-06 05:56 UTC, AlekseyAnt commented on src/components/AboutUs/AboutUs.tsx
> +type StateType = {
лучше PropType и StateType определить как интерфейсы

2021-10-06 08:24 UTC, KachusovStepan commented on src/components/AboutUs/AboutUs.tsx
> +type PropType = {
Я создал файл `src/common/types.ts` .
Перенес типы types и интерфейсы Props, State компонентов в `src/common/types.ts` .
Пока закомментировал определения типов и интерфейсов в файлах компонентов.

2021-10-06 08:25 UTC, KachusovStepan commented on src/interfaces/user/User.ts
> +export interface User {
Изменил имена интерфейсов, чтобы они начинались на "I"
Они должны быть в файле `src/common/types.ts`

2021-10-06 08:27 UTC, KachusovStepan commented on src/components/AboutUs/AboutUs.tsx
> +type StateType = {
Определил интерфейсы Props и State для компонентов
Назвал: `I<component_name>`Props и `I<component_name>`State
Поместил их в файл `src/common/types.ts`

2021-10-06 19:21 UTC, KachusovStepan commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +            .sort((first: any, second: any) => {
Добавил более точные типы, старался избавиться от `any`
Но в коде, работающем с `2-gis`, все же остались `@ts-ignore` и `any`
Следует ли еще точнее определить типы и нужно ли типизировать 2-gis?

2021-10-06 19:23 UTC, KachusovStepan commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +// type StateType = {
Кажется, удалил большинство закомментированного кода в `src/api`, `src/common`, `src/components`, `src/helpers`

2021-10-09 08:45 UTC, KachusovStepan commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +// type StateType = {
Удалил еще некоторый пропущенный закомментированный код

2021-10-13 07:44 UTC, merged