Tree markers
Yekaterinburg-Tree-Map/ekbtrees-frontend pull request #24
Opened 2021-11-02 13:37 UTC by KachusovStepan

…ng 2gis markers with DivIcon and circles), added types for cluster and regular tree data

2021-11-10 07:16 UTC, vvadik commented on src/common/types.ts
> +    id: number;//string | number;
а зачем коммент?

2021-11-10 07:18 UTC, vvadik requested changes

2021-11-10 07:18 UTC, vvadik commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +                        <div key={index}/*{tree[treeKey].title}*/ className={cn([styles.blockWrapper, styles.blockWrapperDesktop])} /*key={key}*/>
и тут

2021-11-10 07:18 UTC, vvadik commented on src/components/EditTreeForm/EditTreeForm.tsx
> +        // ];
=)

2021-11-10 14:57 UTC, KachusovStepan commented on src/common/types.ts
> +    id: number;//string | number;
Спасибо)
Я обычно оставляю старый вариант до ревью, нужно будет удалить

2021-11-10 15:22 UTC, KachusovStepan commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +                        <div key={index}/*{tree[treeKey].title}*/ className={cn([styles.blockWrapper, styles.blockWrapperDesktop])} /*key={key}*/>
Спасибо, кажется, исправил)

2021-11-10 15:23 UTC, KachusovStepan commented on src/components/EditTreeForm/EditTreeForm.tsx
> +        // ];
Спасибо, кажется, исправил)

2021-11-12 07:35 UTC, AlekseyAnt requested changes

2021-11-12 07:35 UTC, AlekseyAnt commented on src/components/Map/treeSpeciesColors.ts
> +    "Дугласия (лжетсуга) Мензиеза": "#37A603",
1) Думаю стоит использовать id породы как ключ, а название можно в комментарии написать
2) По хорошему бы цвет унести на бэк, чтобы потом вслучае чего не меняли фронт.

2021-11-12 07:35 UTC, AlekseyAnt commented on src/components/Map/GeojsonLayer.tsx
> +		if (mapState === 3) {
думаяю можно убрать

2021-11-12 09:42 UTC, KachusovStepan commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +    private conditionAssessmentOptions = [
Создал файл `common/treeForm.ts`, перенес как константы `conditionAssessmentOptions`, `treeStatusOptions`, `treePlantingTypeOptions ` и импортировал в компоненты  `EditTreeForm`, `AddNewTreeForm`

2021-11-12 09:54 UTC, KachusovStepan commented on src/components/Map/GeojsonLayer.tsx
> +		if (mapState === 3) {
Удалил не используемый if

Иногда приходит предупреждение:
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`
Кажется, это связано с запросом геопозиции.
Пытался исправить с помощью `navigator.geolocation.watchPosition`, очищая обработчик перед удалением компонента.
(Раньше при использовании `map.locate({watch: true})`  это предупреждение приходило чаще, карта была null  и не получалось снять обработчик)

Также есть предупреждение:
`Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (615587 px). Occurrences of will-change over the budget will be ignored.`
Можете подсказать, пожалуйста, следует ли пытаться исправить это сейчас?

2021-11-12 10:04 UTC, KachusovStepan commented on src/components/Map/treeSpeciesColors.ts
> +    "Дугласия (лжетсуга) Мензиеза": "#37A603",
Спасибо, было бы отлично получать соответствие породы и цвета из базы)
Возможно также для компонентов `EditTreeForm`, `AddNewTreeForm` тип посадки, внешнее состояние и статус дерева
Дмитрий написал команде бека, постараюсь исправить, как только они добавят в api

2021-11-15 16:26 UTC, AlekseyAnt commented on src/components/Map/GeojsonLayer.tsx
> +		if (mapState === 3) {
Предупреждение "Will-change memory ..." потом починим. А вот предупреждения "Can't perform a React ..." надо бы понять при каких случаях это происходит.

2021-11-15 16:29 UTC, AlekseyAnt commented on src/components/Map/treeSpeciesColors.ts
> +    "Дугласия (лжетсуга) Мензиеза": "#37A603",
Тогда пока так оставляет. Как только появиться порода в рест-методе, то создадим задачку рефакторинг фронта

2021-11-16 13:55 UTC, merged