Перезапрос токена #13
Yekaterinburg-Tree-Map/ekbtrees-frontend pull request #25
Opened 2021-11-09 12:31 UTC by vvadik

Если остается менее 10 минут до истечения срока годности токена, то при запросе он обновится. По умолчанию токен годен пол часа

2021-11-12 07:12 UTC, AlekseyAnt requested changes

2021-11-12 07:43 UTC, vvadik commented on src/helpers/requests.ts
> +		if(decoded_token && decoded_token.exp - Math.round(Date.now() / 1000) < 600) {
Так, а что по итогу изменить? Чтобы запрашивался только по истечению времени?
А зачем вызывать синхронно?

2021-11-15 10:53 UTC, AlekseyAnt commented on src/helpers/requests.ts
> +		if(decoded_token && decoded_token.exp - Math.round(Date.now() / 1000) < 600) {
Да, чтобы запрашивать токен по истечению времени. Синхрононо - чтобы сначала обновился токен, а затем выполнился рест, который использует новый токен

2021-11-22 05:11 UTC, vvadik commented on src/helpers/requests.ts
> +		if(decoded_token && decoded_token.exp - Math.round(Date.now() / 1000) < 600) {
сделал перезапрос токена если ему осталось менее 10 секунд
кажется он и так работает синхронно, сначала вызывается метод refreshtoken и если токен обновляется, то дальше запрос идет уже с новым токеном

2021-11-23 12:10 UTC, AlekseyAnt requested changes

2021-11-23 12:10 UTC, AlekseyAnt commented on src/helpers/requests.ts
> +		this.refreshToken();
метод refreshToken может не успеть отработать перед получение токена.
```javascript
this.refreshToken()
      .then(() => {
          const token = cookies.get('AccessToken');
          ...
      })
```

2021-11-23 12:10 UTC, AlekseyAnt commented on src/helpers/requests.ts
> +		}
```javascript
else {
    return Promise.resolve();
}
```

2021-12-01 06:59 UTC, merged