Add Tree fix
Yekaterinburg-Tree-Map/ekbtrees-frontend pull request #38
Opened 2021-11-18 20:38 UTC by KachusovStepan

added cancel button while adding new tree, probably fixed double requests (removed event listener from zoomend)

2021-11-19 10:38 UTC, KachusovStepan commented on src/components/Map/GeojsonLayer.tsx
> +		if (accuracy > 300) return; // FIXME: too low accuracy
Часто геолокация отображается с плохой точностью и большим радиусом погрешности
Я использовал:
`navigator.geolocation.watchPosition(updateUserGeolocation, () => {}, { enableHighAccuracy: true });`

Кажется, она со временем становится точнее, пока поставил порог в 300 метров, если accuracy > 300 метров, то не изменяю отрисовку местоположения

Можете подсказать, пожалуйста, следует ли искать другое решение?

2021-11-22 09:55 UTC, AlekseyAnt requested changes

2021-11-22 09:55 UTC, AlekseyAnt commented on src/components/Map/GeojsonLayer.tsx
> +	IMapDataSeparateTrees, MapContainerCoords
MapContainerCoords на следующуую строку перенести нужно

2021-11-22 09:55 UTC, AlekseyAnt commented on src/components/Map/GeojsonLayer.tsx
> +	// useEffect(() => {
можно убрать

2021-11-22 09:55 UTC, AlekseyAnt commented on src/components/Map/GeojsonLayer.tsx
> +		if (accuracy > 300) return; // FIXME: too low accuracy
Пока думаю, что можно не искать

2021-11-22 09:55 UTC, AlekseyAnt commented on src/components/Map/GeojsonLayer.tsx
> +	// const markerLayerRef = useRef<any | null>(null);
можно убрать

2021-11-22 09:55 UTC, AlekseyAnt commented on src/components/Map/GeojsonLayer.tsx
> +let lastLambda: any = null;
Пока не придумал, в процессе

2021-11-22 20:30 UTC, KachusovStepan commented on src/components/pages/Tree.tsx
> +				if (succ) {
Я создал новый компонент Modal и использовал в компонентах Tree, AddNewTreeForm, EditTreeForm

2021-11-22 20:34 UTC, KachusovStepan commented on src/components/pages/Tree.tsx
> +		getMyTrees().then(trees => {
Следует ли предположить, что у дерева есть поле, например, `own`, и если оно `false `или его нет, то считать, что дерево не наше?
Или пока оставить так и исправить, когда изменится Api?

2021-11-23 12:04 UTC, AlekseyAnt requested changes

2021-11-23 12:04 UTC, AlekseyAnt commented on src/components/pages/Tree.tsx
> +		if (this.treeId && this.isMyTree) {
Здесь лучше перед запросом на удаление открыть модылку с подтверждение "действительно ли я хочу удалить дерево"

2021-11-23 14:30 UTC, AlekseyAnt commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +                this.setState({modalShow: true, modalMessage: 'Дерево успешно добавлено!', successfullyAdded: true});
оставляет

2021-11-23 14:37 UTC, AlekseyAnt commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +                this.setState({modalShow: true, modalMessage: 'Дерево успешно добавлено!', successfullyAdded: true});
но нужно при возврате на карту изменить масштаб карты близкий к тому, что у нас был при добавлении дерева

2021-12-03 10:14 UTC, merged