Сlient-side form validation
Yekaterinburg-Tree-Map/ekbtrees-frontend pull request #46
Opened 2021-12-04 10:38 UTC by KachusovStepan

2021-12-07 11:58 UTC, AlekseyAnt requested changes

2021-12-09 12:34 UTC, KachusovStepan commented on src/components/EditTreeForm/EditTreeForm.tsx
> +    convertIEditedTreeToIJsonTree(tree: IEditedTree) {
Кажется, я зря добавил преобразование в IPostJsonTree, так как новый метод сохранения принимает тело в формате очень похожем на формат, используемый при добавлении нового дерева.
Возможно ли обойтись только IJsonTree?

2021-12-12 12:35 UTC, AlekseyAnt commented on src/components/EditTreeForm/EditTreeForm.tsx
> +    convertIEditedTreeToIJsonTree(tree: IEditedTree) {
Думаю да

2021-12-12 12:59 UTC, AlekseyAnt requested changes

2021-12-12 12:59 UTC, AlekseyAnt commented on src/components/EditTreeForm/EditTreeForm.tsx
> +    IPostJsonTree, INewTree, IGeographicalPoint,
IPostJsonTree, INewTree, IGeographicalPoint -  не используются

2021-12-12 12:59 UTC, AlekseyAnt commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +                    title: 'Порода*',
1) Предлагаю поменять визуально местам породу поле "Порода" и "Возраст", что обязательные поля шли вперед на форме. 
2) Звездочку луше либо css стилями добавить, либо в момент отрисовки поля, если есть поле обязательно. -> в ITreeProperty нужно добавить поле required

2021-12-12 12:59 UTC, AlekseyAnt commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +                                required={treeKey === "speciesId"}
required={treeKey.required}

2021-12-14 05:59 UTC, AlekseyAnt approved these changes

2021-12-14 05:59 UTC, AlekseyAnt commented on src/components/ProfileSettings/actions.ts
> +    console.log(JSON.stringify(data));
нужно убрать

2021-12-14 05:59 UTC, AlekseyAnt commented on src/components/EditTreeForm/actions.ts
> +export const deleteFile = (fileId: number | string) => {
Стоит этот экшен вынести как обший для EditTreeForm и AddNewTreeForm

2021-12-14 05:59 UTC, AlekseyAnt commented on src/components/ProfileSettings/ProfileSettings.tsx
> +        // let newPassword = prompt("Новый пароль"); // TODO: Better to do input in another way
если не нужно, то нужно убрать

2021-12-14 07:09 UTC, merged