Redesign auth2
Yekaterinburg-Tree-Map/ekbtrees-frontend pull request #68
Opened 2022-04-27 06:13 UTC by Knyazzini

Хэдер, футер, форма регистрации и логина

2022-05-04 16:59 UTC, AlekseyAnt requested changes

2022-05-04 16:59 UTC, AlekseyAnt commented on src/components/App/App.module.css
> +.switch {
Кажется эти стили не используется App

2022-05-04 16:59 UTC, AlekseyAnt commented on src/components/App/App.tsx
> +                <div className={this.state['theme'] === 'light' ? 'background-white' : 'background-gray'}>
Лучше определение className вынести в отдельную переменную

2022-05-04 16:59 UTC, AlekseyAnt commented on src/components/Footer/Footer.tsx
> +                    <span className={styles.email}>Email: example@example.com</span>
добавь mailto

2022-05-04 16:59 UTC, AlekseyAnt commented on src/components/Home/Home.tsx
> +  constructor(props: IHomeProps) {
конструктор можно убрать

2022-05-04 16:59 UTC, AlekseyAnt commented on src/components/Home/Home.tsx
> +        <img src={volontary} className={styles.volontaryImage} />
voluntary

2022-05-04 16:59 UTC, AlekseyAnt commented on src/components/Home/Home.tsx
>          {this.props.user ? null : this.renderGetStartSection()}
Вроде renderGetStartSection мы должны вызывать всегда

2022-05-04 16:59 UTC, AlekseyAnt commented on src/components/Home/Home.tsx
> +          <div style={{ display: "flex", marginTop: "55px" }}>
стоит удалить

2022-05-04 16:59 UTC, AlekseyAnt commented on src/components/Logo/Logo.module.css
> +    margin-bottom: 0px;
margin-bottom - лишний

2022-05-04 16:59 UTC, AlekseyAnt commented on src/components/SharedHeader/SharedHeader.tsx
> +
лишний отступ

2022-05-05 09:38 UTC, Knyazzini commented on src/components/Home/Home.tsx
> +          <div style={{ display: "flex", marginTop: "55px" }}>
Оставить одну картинку?

2022-05-05 09:46 UTC, Knyazzini commented on src/components/MobileHeader/MobileHeader.tsx
>  					<button className={styles.burgerBtn} onClick={this.handleClick}>
Если речь про burgerBtn, увеличил.

2022-05-15 13:07 UTC, AlekseyAnt requested changes

2022-05-15 13:07 UTC, AlekseyAnt commented on src/components/Login-form/Login-form.module.css
>      height: 550px;
давай здесь сдалаем 600px. при переходе с "Регистрация" форма как-будто бы скачет.

2022-05-15 13:07 UTC, AlekseyAnt commented on src/components/Login-form/Login-form.tsx
> +                <input type="text" placeholder="Почта" id="userLogin" onChange={this.handleChange('email')} required />
Высоту полей надо бы сделать такую же как на форме "Регистрация" (примероно 45px)

2022-06-01 10:09 UTC, AlekseyAnt requested changes

2022-06-08 13:39 UTC, Knyazzini commented on src/components/TreeLists/TreeLists.tsx
> +                <div>&mdash;&mdash; Список деревьев</div>
Поменял шрифт в табличке

2022-06-12 06:28 UTC, Knyazzini commented on src/components/Registation-form/Registration-form.tsx
>      render() {
Синхронизировал, теперь верхняя плашка "Привет друг"/"С возвращением" появляется только на мобилках.

2022-06-19 20:54 UTC, AlekseyAnt requested changes

2022-06-19 20:54 UTC, AlekseyAnt commented on src/components/AddNewTreeForm/AddNewTreeForm.tsx
> +                    debugger;
Нужно убрать

2022-06-19 20:54 UTC, AlekseyAnt commented on src/components/AddNewTreeForm/AddNewTreeForm.module.css
> +    .imagesWrapper {
нужно box-shadow добавить

2022-06-19 20:54 UTC, AlekseyAnt commented on src/components/TreeLists/TreeLists.tsx
> +            <NavLink to={getTreeLink(id)} className={styles.treeTableRowMobile} key={id}>
Верстка едет, если не задать "Возраст" и/или "Высота"

2022-06-19 20:54 UTC, AlekseyAnt commented on src/components/Footer/Footer.tsx
> +                        <a href="https://t.me/parklandekb"><img className={styles.image} src={telegramIcon} alt={"telegram"} /></a>
Думаю стаит добавить target="_blank"

2022-06-19 20:54 UTC, AlekseyAnt commented on src/components/Footer/Footer.tsx
> +                    <NavLink className={styles.link} exact to='/saveTrees' activeClassName="active">Политика конфиденциальности</NavLink>
Тут ссылка должна вести на страницу "Политика конфиденциальности"

2022-06-20 07:37 UTC, merged