change max file size, change descriptions
Yekaterinburg-Tree-Map/ekbtrees-frontend pull request #72
Opened 2022-11-23 13:15 UTC by Knyazzini

Макс размер 50мб

2022-11-30 04:41 UTC, AlekseyAnt approved these changes

2022-11-30 04:41 UTC, AlekseyAnt commented on src/components/Map/GeojsonLayer.tsx
> +        console.log(map.getZoom(), 'zoom');
думаю стоит убрать

2023-01-15 19:53 UTC, AlekseyAnt requested changes

2023-01-15 19:53 UTC, AlekseyAnt commented on src/components/TreeForm/TreeForm.tsx
> +                    <span className={styles.rowName}>Вид</span>
Род/вид

2023-01-15 19:53 UTC, AlekseyAnt commented on src/components/TreeLists/TreeLists.tsx
> +        species: 'Вид'
Род/вид

2023-01-15 19:53 UTC, AlekseyAnt commented on src/components/TreeLists/TreeLists.tsx
> +                    <span>Вид</span>
Род/вид

2023-01-15 19:53 UTC, AlekseyAnt commented on src/components/Map/GeojsonLayer.tsx
> +        weight:item.approvedByModerator ? 1 : 0,
Насколько я помню, красной границей мы помечаем круг, если дерево еще не подтвердили

2023-01-16 18:39 UTC, Knyazzini commented on src/components/Map/GeojsonLayer.tsx
> +        weight:item.approvedByModerator ? 1 : 0,
Ага, перепутал, обратно поставлю

2023-01-18 17:20 UTC, Knyazzini commented on src/components/Tree/Tree.tsx
> +            <div className={styles.comment}>Примечание: {" "}
1. "У блока .commentTitle шрифт жирный." специально сделал коммент жирным, сделать все нежирным? Кажется читать большой жирный текст не очень. Но сделаю пока все жирным тогдла

2023-01-19 11:48 UTC, AlekseyAnt approved these changes

2023-01-19 11:50 UTC, merged